# This file was generated by GoReleaser. DO NOT EDIT.
cask "termchat" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "cd221c8821521d454b9019d668b90c4f60bc6dd9d949b69a7c0adca5f819a422"
      url "https://github.com/sw4p/termchat/releases/download/v#{version}/termchat_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7a0405162710f7452929c0ed5621ad7d3371725617ab5c528b69cf24f0c1316d"
      url "https://github.com/sw4p/termchat/releases/download/v#{version}/termchat_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7f69857c034fdfb932b4ffd342a93a581083d1265718f6a4ce652a275d1d9604"
      url "https://github.com/sw4p/termchat/releases/download/v#{version}/termchat_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "591c1ba79491147fc0bad1b3a7aa443b5d7b611b873afefca7b1b61a7a8d5f7d"
      url "https://github.com/sw4p/termchat/releases/download/v#{version}/termchat_#{version}_linux_amd64.tar.gz"
    end
  end

  name "termchat"
  desc "Chat with a random stranger on your LAN, end-to-end encrypted, from the terminal"
  homepage "https://github.com/sw4p/termchat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termchat"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termchat"]
    end
  end

  # No zap stanza required
end
