# This file was generated by GoReleaser. DO NOT EDIT.
cask "termchat" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "e7f406dad4a6136d5972068b36f3963395b2d32740309b690c1616fdbce1adb8"
      url "https://github.com/sw4p/termchat/releases/download/v#{version}/termchat_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "004e9736d5bc40a15107f42717b414c3e25e4cc51938900aab9c59159fa83560"
      url "https://github.com/sw4p/termchat/releases/download/v#{version}/termchat_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "81c983a67c8f983ee68fbfd0eabde5a8864518a16195411936cb1370e72823e2"
      url "https://github.com/sw4p/termchat/releases/download/v#{version}/termchat_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dc0758a95d66907ff2852a8ef0c84889b2b307c1209355ea787af44d582d1840"
      url "https://github.com/sw4p/termchat/releases/download/v#{version}/termchat_#{version}_linux_amd64.tar.gz"
    end
  end

  name "termchat"
  desc "Chat with a random stranger on your LAN, end-to-end encrypted, from the terminal"
  homepage "https://github.com/sw4p/termchat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termchat"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termchat"]
    end
  end

  # No zap stanza required
end
